### ISSUE TITLE
Move the interface to the cloud Or think about a way to make it more stable.

### ISSUE THREAD

**Issue by cegme** [oudalab/fajita#109]
We need to look at that options for hosting node.js on google app engine. We also need to look at the [quota](https://cloud.google.com/appengine/docs/quotas), we will likely remain in the free tier. We may need to ensure that data transferred is minimized.
We can either use [node.js](https://cloud.google.com/appengine/docs/flexible/nodejs/) directly or use [docker on the custom runtime](https://cloud.google.com/appengine/docs/flexible/custom-runtimes/quickstart).

**Comment by YanLiang1102** [comment]
@cegme  looks like the google app engine is not free... can they provide free service for research purpose, I need to provide my credit card info in order to do the free trial.

**Comment by YanLiang1102** [comment]
We make the python code to restart the server when it is down.
And after it is running it is not run as a forever process even though we use forever under python code to start the server , so the way to turn down the service is:
sudo fuser 8084/tcp,
and we will find the pid
using kill -9 pid to kill the process.

**Comment by YanLiang1102** [comment]
we solve this by using nohup
