### ISSUE TITLE
Coders can't access their "Most Recent Activities"

### ISSUE THREAD

**Issue by manarlandis** [oudalab/fajita#110]
Coders need to know if their work is saved. I took and sent screenshots of "Flagged Summary" for now, but they still need to have access to their work. I can see the date of last coding on nouns, but I can't tell if their work on verbs was saved since I still can't see the date on "verbs Flagged Summary."

**Comment by YanLiang1102** [comment]
@manar, now the verb shows the tagging time.
Also all the students should have access to the flagged summary.
And they have access to track your performance button on the top left basically count how much words and sentences does the current login user tagged.
