### ISSUE TITLE
Delete upper row of (Country, Primary role, Secondary role, and verb list)

### ISSUE THREAD

**Issue by manarlandis** [oudalab/fajita#120]
@YanLiang1102 if you commit your noun coding then move to code another noun within the same text, the data will be deleted from the second rows only. clearing only half of the data, is misleading. I believe this causes the coders to sometimes forget to use the clear button, as they think the data is clear when half of it disappears or if they are coding a noun that does not need both primary and secondary role where they might clear only the data that they need to put new one instead. 
Clear button is helpful and working, but it is not solving the problem entirely. I think combining both clear button and keeping only one row of each coding option, will help the coders avoid leaving data from previous coding.

**Comment by YanLiang1102** [comment]
1.Add a scroll bar on the second roll to achieve the first row's functionality.
2. reorganize the interface.

**Comment by YanLiang1102** [comment]
Already find a bug, I can't change whatever put in the combo box it will keep the old value.
