### ISSUE TITLE
Arabic Synonyms API not working.

### ISSUE THREAD

**Issue by YanLiang1102** [oudalab/fajita#148]

**Comment by YanLiang1102** [comment]
Most of  them just return null or exception for arabic which not happen for english.

**Comment by ahalterman** [comment]
Is it returning synonyms for some of them, at least? Or are all the answers null/exceptions?

**Comment by YanLiang1102** [comment]
@ahalterman  using the words I tried like 10 of them all of them return either exception or null.

**Comment by ahalterman** [comment]
I think there was an s3 permissions problem that was preventing the Arabic models from downloading. I just opened up read permissions. Can you try again?

**Comment by YanLiang1102** [comment]
I will try later today Andy Thank you.

2017-03-14 12:05 GMT-05:00 Andy Halterman <notifications@github.com>:

**Comment by YanLiang1102** [comment]
Instead of using the container using a local flask to accept the request.

**Comment by YanLiang1102** [comment]
finally make it work test with "أول"

**Comment by YanLiang1102** [comment]
I change the code to load the library on hanover and now teh synonym service is run locally on hanover with port 9090 instead of using the container....

**Comment by YanLiang1102** [comment]
now to start the service code , go to otherHelperCode/synonym_api.py
