### ISSUE TITLE
Add user authentication

### ISSUE THREAD

**Issue by ahalterman** [oudalab/fajita#5]
Coders should have to log into the coding dashboard with their own username and password. There are two purposes for this:
- basic authentication because we'll be running the server publicly on the open internet
- logging with each commit which student did it for quality control/evaluation purposes

We discussed using OAuth or Facebook login, or we can use a build in simple HTTP auth.

**Comment by YanLiang1102** [comment]
might need to run 
npm install node-gyp -g
and npm install bcrypt -g
for node globally when deploy this app on another machine, since there is some install with npm install bcrypt
