### ISSUE TITLE
Figure out coding output and storage

### ISSUE THREAD

**Issue by ahalterman** [oudalab/fajita#6]
After coding, we'll have a new gold standard coded event and several new dictionary entries. We need to figure out:
- [ ] How the gold standard event will be formatted
- [ ] Where the gold standard event will be stored
- [ ] How the dictionary entries will be formatted
- [ ] Where the dictionary entries will be stored

**Comment by YanLiang1102** [comment]
Correct me if I am wrong Andy,
for gold standard coded event:
(doc_id, sentence_index, actor code, verb code, target code, event publish date,sure--boolean,userId, taggingTime)
isssue #7
for dictioanry entries:
- [ ] 1. (word being tagged, tagged result, dateStarted, dateEnded,userId, taggingTime) dateStarted and deteEnded only applied for actor and target tagging, for verb it should be null.
- [ ] 2. also we need a stem library to get the stem version for the key value
