### ISSUE TITLE
Users get the same story when coding at the same time

### ISSUE THREAD

**Issue by ahalterman** [oudalab/fajita#73]
Right now, if two users are coding at the same time, they'll get the same sentence. Each user should get a random document instead. Various approaches: http://stackoverflow.com/questions/2824157/random-record-from-mongodb

**Comment by PTB-OEDA** [comment]
OK, this is an issue. We have this randomized here at UTD and have randomized the suggested inputs that the user sees to reduce response / annotator biases.  Need to make this a common feature across the tools.

**Comment by YanLiang1102** [comment]
fixed and we need to always keep out data format to be tagged:false, instead of tagged:0,
in order for the random skip query to work.
and this is what I am currently doing db.sentences.update({tagged:0},{$set:{tagged:false}},{multi:true}) 
with 10k records in our test db
