### ISSUE TITLE
Update options for 1st and 2nd roles

### ISSUE THREAD

**Issue by ahalterman** [oudalab/fajita#74]
Some of the 1st role and 2nd role codes are missing from the interface. Update the JSON and give to Yan.

**Comment by ahalterman** [comment]
Here are the updated codes for each:
[Actor_codes.txt](https://github.com/oudalab/fajita/files/413654/Actor_codes.txt)

**Comment by ahalterman** [comment]
Oh, also, we need a blank line for each of these. This came up when I incorrectly selected a role code for an actor that didn't have one, and then there was no way to un-do.

**Comment by YanLiang1102** [comment]
fixed
