### ISSUE TITLE
Sort CAMEO codes by text file in dropdown

### ISSUE THREAD

**Issue by ahalterman** [oudalab/fajita#77]
Having the CAMEO event codes in their initial order will help coders find the correct code much faster since similar events are grouped together.

We talked about adding a column to the text file that's 1:nrow, sorting by it, and then not displaying it.

**Comment by PTB-OEDA** [comment]
We are facing up to this in the verb translation here at UTD. You need to present the verbs in their hierarchy so coders get them right.  A good example is 08 -> 087 -> 0874 on types of "yield" or de-escalation. So giving the verbs as part of their hierarchy in the CAMEO ontology makes the most sense (2-digit, then 3- and any 4-).

Further, you can see how our future interface does this here (in a few days -- it is not implemented yet): 

myprojectr.appspot.com

**Comment by ahalterman** [comment]
Sorting it according to the order in the file (attached) preserves the hierarchy. 
[CAMEO_Verb_Codes.txt](https://github.com/oudalab/fajita/files/415718/CAMEO_Verb_Codes.txt)

**Comment by YanLiang1102** [comment]
this has been fixed and up on the server
