### ISSUE TITLE
Add missing role codes

### ISSUE THREAD

**Issue by ahalterman** [oudalab/fajita#99]
A couple of codes are missing from the dropdown menus. I looked through the code to try to find where they're defined so I could add them myself and submit a PR, but I couldn't figure out where they're added. Could you tell me where they're defined? Future users will need to be able to add and delete codes.

Here are the codes to add:
1. to the "country" list: IGO (intergovernmental organizations), IMG (international militarized groups)
2. To the primary role: ELI (Elites, former governmental officials), PTY (Political parties)

**Comment by YanLiang1102** [comment]
@ahalterman  it is not added into the javascript code, it is using a python script directly insert into mongodb

**Comment by YanLiang1102** [comment]
@ahalterman , Andy, I just took a look, looks like IGO, IMG and PTY are already there.
I just insetr ELI there for you.
BTW, here is the code how to add role in db.
https://github.com/oudalab/fajita/blob/master/otherHelperCode/eventDataPythonCode.ipynb

**Comment by ahalterman** [comment]
👍
